### ISSUE TITLE
Handling unicode as data when feeding logtop

### ISSUE THREAD

**Issue by Shedna** [JulienPalard/logtop#1]
You should think about doing .encode('utf8') by logtop when sending unicode data in function feed().

**Comment by JulienPalard** [comment]
I updated the example to use Python 3. According to swig documentation:

> When a Python string is passed as a parameter, the C function receives a pointer to the raw data contained in the string.

Which is fine as logtop does not have to understand the data, let's not spend time encoding/decoding for nothing.
