### ISSUE TITLE
Package for Void linux

### ISSUE THREAD

**Issue by cr6git** [JulienPalard/logtop#6]
Hi @JulienPalard !

A package is now available for Void linux, see [0ca7e30](https://github.com/voidlinux/void-packages/commit/0ca7e3013ece8b4e7eef61b2eebc41ffcd8abb27) :tada:

`xbps-install -S logtop`

Regards.

**Comment by JulienPalard** [comment]
Hi @cr6git, I do not know Void linux... wait now I know it. Thanks, I'll update the README.

**Comment by JulienPalard** [comment]
REAMDE updated, thanks again!
